FROM tomcat:10-jdk17

# Remove default apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR file
COPY AjaraBazar.war /usr/local/tomcat/webapps/ROOT.war

# Use Railway's PORT or default to 8080
ENV PORT=8080

# Configure Tomcat to use the PORT from environment
RUN sed -i "s/port=\"8080\"/port=\"\${PORT}\"/" /usr/local/tomcat/conf/server.xml

# Expose port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
